/* nedb.h — C API for the NEDB DAG storage engine (ITC node backend)
 *
 * Generated by cbindgen at build time (see nedb-ffi/build.rs).
 * Hand-maintained header for IDE / pre-build use.
 *
 * This header is included by src/dbwrapper.h to replace LevelDB with NEDB
 * as the block index and chainstate backend of the ITC node.
 *
 * Phase 1: HashMap-backed in-process store (proves the seam, no external deps).
 * Phase 2: nedb_core_v2::Db — BLAKE2b chain head, MVCC AS OF, causal DAG,
 *           AES-256-GCM encryption, deterministic state roots.
 *
 * © Interchained LLC × Claude Sonnet 4.6
 */

#ifndef NEDB_FFI_H
#define NEDB_FFI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

/* ---- Opaque types ---------------------------------------------------- */

/** Opaque database handle.  Obtain via nedb_open(); free via nedb_close(). */
typedef struct NedbHandle NedbHandle;

/** Opaque snapshot iterator.  Obtain via nedb_iter_new(); free via nedb_iter_free(). */
typedef struct NedbIter NedbIter;

/* ---- Batch operation ------------------------------------------------- */

/**
 * A single operation in a batch write.
 * Set value = NULL to request deletion of the key.
 */
typedef struct NedbOp {
    const unsigned char *key;
    size_t               key_len;
    const unsigned char *value;       /* NULL = delete this key */
    size_t               value_len;
} NedbOp;

/* ---- Database lifecycle --------------------------------------------- */

/**
 * Open (or create) a NEDB database at @path.
 * @dek   AES-256-GCM data-encryption key as a 64-char hex string, or NULL
 *        for plaintext storage.  Passed to nedbd --dag as NEDB_TMK in Phase 2.
 *
 * Returns an opaque NedbHandle* on success, NULL on failure.
 * Caller must eventually call nedb_close().
 */
NedbHandle *nedb_open(const char *path, const char *dek);

/** Close the database and free all resources.  Safe to call with NULL. */
void nedb_close(NedbHandle *handle);

/**
 * Enable (1) or disable (0) causal provenance for writes on @handle.
 *
 * Default: enabled. Disable ONLY for lookup-table databases whose causal lineage
 * is already intrinsic to the payload — the block index is the canonical case
 * (every CDiskBlockIndex carries hashPrev, so the block→parent edge is in the
 * data). With provenance off, writes skip the read-before-write that loads the
 * prior object from disk just to copy its hash into caused_by; the engine still
 * tracks each entry's prev from the in-memory id-index, so get()/latest-write-
 * wins is unchanged. Only the caused_by DAG edges are omitted for this DB.
 *
 * NEVER disable for the chainstate — there caused_by IS the consensus UTXO
 * causal history. (Block index and chainstate are separate NEDB databases.)
 */
void nedb_set_provenance(NedbHandle *handle, int enabled);

/**
 * Number of provenance reads avoided so far on @handle (diagnostic).
 * Returns 0 in Phase 1.
 */
uint64_t nedb_reads_sliced(NedbHandle *handle);

/* ---- Single-record operations --------------------------------------- */

/**
 * Read the value for @key.
 *
 * @key / @key_len         Binary key.
 * @value_out              Set to a heap-allocated copy of the value.
 * @value_len_out          Set to the value byte length.
 *
 * Returns:
 *   0   — found; caller must free *value_out via nedb_free_value().
 *   1   — key not found; *value_out is unchanged.
 *  -1   — error (null handle or null key).
 */
int nedb_get(NedbHandle          *handle,
             const unsigned char *key,       size_t  key_len,
             unsigned char      **value_out, size_t *value_len_out);

/** Free a value buffer returned by nedb_get(). */
void nedb_free_value(unsigned char *ptr, size_t len);

/**
 * Batch point-read: fetch @ops_len values by key, in PARALLEL on Phase 2
 * (rayon over the engine's get — the read-side twin of nedb_batch_write).
 *
 * Inputs reuse the NedbOp array: only `key` / `key_len` are read; `value` /
 * `value_len` are ignored. The caller pre-allocates two output arrays of
 * length @ops_len. On return, for each i:
 *   values_out[i]     — a freshly heap-allocated value buffer (free via
 *                       nedb_free_value()), or NULL when the key is absent.
 *   value_lens_out[i] — its byte length, or 0 when the key is absent.
 *
 * Returns 0 on success, -1 on a null-argument error.
 */
int nedb_get_batch(NedbHandle      *handle,
                   const NedbOp    *ops,            size_t  ops_len,
                   unsigned char  **values_out,
                   size_t          *value_lens_out);

/**
 * Write @value under @key.
 * In Phase 2 this is a causal PUT with caused_by = previous seq for this key,
 * advancing the BLAKE2b chain head and incrementing the monotonic sequence.
 *
 * Returns 0 on success, -1 on error.
 */
int nedb_put(NedbHandle          *handle,
             const unsigned char *key,   size_t key_len,
             const unsigned char *value, size_t value_len);

/**
 * Delete @key (tombstone in Phase 2, BTreeMap removal in Phase 1).
 * Returns 0 on success (including when key does not exist), -1 on error.
 */
int nedb_del(NedbHandle          *handle,
             const unsigned char *key, size_t key_len);

/**
 * Test key existence without returning the value.
 * Returns 1 if found, 0 if not found, -1 on error.
 */
int nedb_exists(NedbHandle          *handle,
                const unsigned char *key, size_t key_len);

/**
 * Returns 1 if the database contains no entries, 0 otherwise, -1 on error.
 */
int nedb_is_empty(NedbHandle *handle);

/* ---- Batch writes --------------------------------------------------- */

/**
 * Atomically apply @ops_len operations from @ops.
 * Puts and deletes are mixed freely.  In Phase 2 this maps to a NEDB
 * group-commit batch (single fsync, single seq advancement).
 *
 * Returns 0 on success, -1 on error.
 */
int nedb_batch_write(NedbHandle    *handle,
                     const NedbOp  *ops,
                     size_t         ops_len);

/* ---- State root ------------------------------------------------------ */

/**
 * Return the current BLAKE2b-512 chain head as a 128-character hex string
 * (null-terminated).
 *
 * In Phase 2 this is the NEDB Merkle root — a deterministic commitment to
 * all storage state at the current sequence number.  Two nodes that have
 * processed identical chains produce identical heads, giving storage-level
 * consensus proof without an external block explorer.
 *
 * Caller must free the returned string via nedb_free_str().
 */
char *nedb_head(NedbHandle *handle);

/** Free a C string returned by any nedb_* function. */
void nedb_free_str(char *s);

/* ---- Chain integrity verification ----------------------------------- */

/**
 * Verify the tamper-evidence of every object in the store (NEDB native).
 *
 * Walks the content-addressed objects and confirms each still hashes to its
 * stored address. This is the storage-layer equivalent of replaying and
 * re-hashing the whole chain, but native and near-instant — the integrity
 * proof the ITC node runs at startup (NEDB Proof-of-Prefix warm boot) before
 * trusting its persisted tip.
 *
 * Returns:
 *    0  — intact (every object verified, zero problems).
 *   >0  — number of objects that failed verification (tampered/corrupt).
 *   -1  — error (null handle).
 */
int nedb_verify(NedbHandle *handle);

/* ---- Bulk scan ------------------------------------------------------- */

/**
 * Callback invoked once per entry during nedb_scan().
 *
 * @key / @key_len      Raw binary key (same bytes as stored by nedb_put/batch).
 * @val / @val_len      Raw binary value.
 * @progress            1-based count of entries delivered so far.
 * @total               Total entry count for this scan (0 = unknown).
 * @ctx                 Caller-supplied context pointer.
 *
 * key/val pointers are only valid for the duration of the callback.
 * Do NOT call nedb_free_value() on them.
 */
typedef void (*NedbScanFn)(const unsigned char *key, size_t key_len,
                           const unsigned char *val, size_t val_len,
                           uint64_t progress, uint64_t total,
                           void *ctx);

/**
 * Scan all entries in the database, invoking @callback for each one.
 *
 * Replaces the iterator pattern for bulk loads (e.g. block-index startup).
 * Provides a progress counter so callers can log without waiting for the
 * entire scan to complete before seeing the first entry.
 *
 * Returns the total number of entries scanned, or 0 on error.
 */
uint64_t nedb_scan(NedbHandle *handle, NedbScanFn callback, void *ctx);

/* ---- Iterator ------------------------------------------------------- */

/**
 * Create a snapshot iterator over the current store contents.
 * The snapshot is taken at iterator creation; subsequent writes are not visible.
 * Caller must free via nedb_iter_free().
 */
NedbIter *nedb_iter_new(NedbHandle *handle);

/** Free an iterator and its snapshot. */
void nedb_iter_free(NedbIter *iter);

/** Position the iterator at the lexicographically first key. */
void nedb_iter_seek_to_first(NedbIter *iter);

/**
 * Seek to the first key >= @key.
 * Returns 1 if a valid position was found, 0 if iterator is exhausted.
 */
int nedb_iter_seek(NedbIter            *iter,
                   const unsigned char *key, size_t key_len);

/** Advance to the next entry. */
void nedb_iter_next(NedbIter *iter);

/** Returns 1 if the iterator points to a valid entry, 0 otherwise. */
int nedb_iter_valid(const NedbIter *iter);

/**
 * Copy the current key into *key_out / *key_len_out.
 * Caller must free via nedb_free_value().
 * Returns 0 on success, -1 on error.
 */
int nedb_iter_key(const NedbIter  *iter,
                  unsigned char  **key_out,
                  size_t          *key_len_out);

/**
 * Copy the current value into *value_out / *value_len_out.
 * Caller must free via nedb_free_value().
 * Returns 0 on success, -1 on error.
 */
int nedb_iter_value(const NedbIter  *iter,
                    unsigned char  **value_out,
                    size_t          *value_len_out);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* NEDB_FFI_H */
